### ISSUE TITLE
Error When Running

### ISSUE THREAD

**Issue by shoelessjp** [Mechazawa/whatbetter-crawler#6]
I get the following error when I try to run:

```
t_raceback (most recent call last):
  File "/usr/local/bin/whatbetter", line 4, in <module>
    __import__('pkg_resources').run_script('whatbetter==1.2', 'whatbetter')
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 1512, in run_script
    exec(script_code, namespace, namespace)
  File "/Library/Python/2.7/site-packages/whatbetter-1.2-py2.7.egg/EGG-INFO/scripts/whatbetter", line 219, in <module>
    
  File "/Library/Python/2.7/site-packages/whatbetter-1.2-py2.7.egg/EGG-INFO/scripts/whatbetter", line 127, in main_
```

Sorry, I'm a complete idiot with things like this.

**Comment by Mechazawa** [comment]
I don't think this is the full traceback (error). Am I mistaken?

**Comment by shoelessjp** [comment]
Actually, I got it fixed. It had to do with the syntax. Apparently I wasn't entering the Torrent ID in correctly.

**Comment by Mechazawa** [comment]
Mistakes happen. Great to hear you got it working
-------- Original message --------From: Jonathan Patten <notifications@github.com> Date: 21/08/2016  02:58  (GMT-04:00) To: Mechazawa/whatbetter-crawler <whatbetter-crawler@noreply.github.com> Cc: Bas <BasBieling@gmail.com>, Assign <assign@noreply.github.com> Subject: Re: [Mechazawa/whatbetter-crawler] Error When Running (#6) 
Actually, I got it fixed. It had to do with the syntax. Apparently I wasn't entering the Torrent ID in correctly.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Mechazawa/whatbetter-crawler","title":"Mechazawa/whatbetter-crawler","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Mechazawa/whatbetter-crawler"}},"updates":{"snippets":[{"icon":"PERSON","message":"@shoelessjp in #6: Actually, I got it fixed. It had to do with the syntax. Apparently I wasn't entering the Torrent ID in correctly."}],"action":{"name":"View Issue","url":"https://github.com/Mechazawa/whatbetter-crawler/issues/6#issuecomment-241242311"}}}
